erDiagram
    USUARIO ||--o{ RESERVA : "realiza"
    EVENTO ||--o{ RESERVA : "tiene"
    
    USUARIO {
        ObjectId _id PK
        string tipo_documento
        string nro_documento_hash
        string nombre
        string apellido
        string email_encrypted
        array historial_compras_ref "Referencias a Reservas"
        timestamp fecha_registro
    }
    
    EVENTO {
        ObjectId _id PK
        string nombre
        ISODate fecha
        string lugar
        int aforo_total
        int entradas_disponibles
        array reservas_activas_ref "Referencias a Reservas"
        string descripcion
        decimal precio
    }
    
    RESERVA {
        string reserva_id PK
        ObjectId usuario_id FK
        ObjectId evento_id FK
        int cantidad_entradas
        decimal monto_total
        string estado "pendiente|confirmada|cancelada"
        timestamp fecha_reserva
        timestamp fecha_expiracion
        string transaction_id
    }