Error al representar el código incrustado

Error de análisis en la línea 5:
...t NoticiaPadreId FK}ENTRADA {int En
----------------------^
Se esperaba 'EOF', 'ESPACIO', 'NUEVA LÍNEA', 'título', 'acc_title', 'acc_descr', 'acc_descr_multiline_value', 'direction_tb', 'direction_bt', 'direction_rl', 'direction_lr', 'CLASSDEF', 'UNICODE_TEXT', 'CLASS', 'STYLE', 'ENTITY_NAME', se obtuvo '}'

Para obtener más información, consulte https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
